# Generated by Django 6.0.3 on 2026-03-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(verbose_name='Pergunta')),
                ('pub_date', models.DateTimeField(verbose_name='Data de publicação')),
            ],
        ),
    ]
